result = apply four 1;
apply f x = f x;
four y = w y;
three y k = (m y k) + (n y k) + (two y k 1 ((n y k) - (m y k)));
z y = (three y y) * y;
w y = z y * three y (z y);
two y k p a = p + (2 * a);
m y k = 4 * k;
n y k = k * (m y k) * (two y k 5 k)
